blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/Engagedly-Inc/tango-api-client/discussions/new?category=q-a
    about: Ask questions and get help from the community and maintainers.

